FROM python:3.8-slim

RUN apt-get update > /dev/null && \
    apt-get upgrade --yes > /dev/null && \
    apt-get install --yes curl libpq-dev gcc > /dev/null && \
    apt-get clean > /dev/null && \
    rm -rf /var/lib/apt/lists/* > /dev/null && \
    pip install --no-cache-dir -U pip setuptools wheel > /dev/null

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python > /dev/null && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

WORKDIR /code

COPY ./pyproject.toml ./poetry.lock* ./

RUN poetry install --no-root --no-dev

COPY ./src ./src

EXPOSE 8080

# ENTRYPOINT ["gunicorn", "main:app", "--chdir", "./src", "--workers", "4", \
#             "--worker-class", "uvicorn.workers.UvicornWorker", "-b", ":8080"]
ENTRYPOINT ["uvicorn", "main:app", "--port", "8080", "--reload", "--app-dir", "./src", "--host", "0.0.0.0"]
